print("We have gathered here today to tell a story")
input()
print("Please answer the following questions to create the story")
input()
name = input("Give a name: ")
city = input("Give a city or town name: ")
emotionfeeling1 = input("Give an emotion/feeling: ")
breakfast = input("Give a food(breakfast): ")
verb = input("Give a verb (present tense): ")
place = input("Give any place (a different one than before): ")
number = input("Give a number: ")
time =input("Give a system of time (e.g. minutes, seconds): ")
emotionfeeling2 = input("Give an emotion/feeling: ")
restaurant = input("Give a restaurant: ")
adjective1 = input("Give an adjective: ")
adjective2 = input("Give an adjective: ")
input()
print("Thank you for answering those questions.")
print("Here is your story:")
input()
print("--------------------------------------------------------------------------------------------")
print(f"Once upon a time, there was an 8th grader named {name}, who lived in {city}.")
print(f"{name} was usually a pretty {emotionfeeling1} person. That morning as {name}")
print(f"was having {breakfast} for breakfast, they decided that they were going to")
print(f"{verb} all the way to {place}. They quickly took off. It took {name} about")
print(f"{number} {time} to get there, and upon arriving they were very {emotionfeeling2}.")
print(f"{name} traveled and did some sight seeing for a few hours, but then got hungry")
print(f"and ate at {restaurant}. Once they finished the very {adjective1} food, {name}")
print(f"decided to head back home. In conclution, {name} thought today was a very {adjective2} day.")
print("The end.")
print("--------------------------------------------------------------------------------------------")